
                                                            
                                                            
PPPPPPPPPPPPPPPPP        QQQQQQQQQ             CCCCCCCCCCCCC
P::::::::::::::::P     QQ:::::::::QQ        CCC::::::::::::C
P::::::PPPPPP:::::P  QQ:::::::::::::QQ    CC:::::::::::::::C
PP:::::P     P:::::PQ:::::::QQQ:::::::Q  C:::::CCCCCCCC::::C
  P::::P     P:::::PQ::::::O   Q::::::Q C:::::C       CCCCCC
  P::::P     P:::::PQ:::::O     Q:::::QC:::::C              
  P::::PPPPPP:::::P Q:::::O     Q:::::QC:::::C              
  P:::::::::::::PP  Q:::::O     Q:::::QC:::::C              
  P::::PPPPPPPPP    Q:::::O     Q:::::QC:::::C              
  P::::P            Q:::::O     Q:::::QC:::::C              
  P::::P            Q:::::O  QQQQ:::::QC:::::C              
  P::::P            Q::::::O Q::::::::Q C:::::C       CCCCCC
PP::::::PP          Q:::::::QQ::::::::Q  C:::::CCCCCCCC::::C
P::::::::P           QQ::::::::::::::Q    CC:::::::::::::::C
P::::::::P             QQ:::::::::::Q       CCC::::::::::::C
PPPPPPPPPP               QQQQQQQQ::::QQ        CCCCCCCCCCCCC
                                 Q:::::Q                    
                                  QQQQQQ                    
